### ISSUE TITLE
read from ffmpeg stream?

### ISSUE THREAD

**Issue by josepowera** [Awexander/audioWhisper#3]
Just wanted to ask if this could work on general ffmpeg input stream and not on Microphone input.

Example: you would point to radio station and this would print transcription to console in live mode. (for example every 3 seconds if it helps)

**Comment by awexandrr** [comment]
Yes. You need to write a code to download the input stream audio in wav format and transcribe the downloaded audio using whisper module. Generally, whisper module can transcribe any audio in wav format.

**Comment by fortypercnt** [comment]
I took audioWhisper as inspiration and implemented a CLI tool that can use whisper directly on livestreams in ffmpeg, transcribing every couple of seconds. You can find it [here](https://github.com/fortypercnt/stream-translator). It can also use streamlink to automatically get .m3u8 files for various streaming sites.

**Comment by awexandrr** [comment]
Nice! Thankyou very much. At first this is what I want to write but unfortunately I didn't know how to and I wrote the code to complement that. Thanks for this!

**Comment by fortypercnt** [comment]
Happy to hear! I have quite a few ideas on how to improve it. E.g. keep audio in "whisper format" (after ffmpeg reencode) in a ringbuffer that is filled every second and always read the last 30s of audio, so that the transcription has more context and can update more often. Or use the streamlink API to open stream from the script and mux the subtitles in directly.

**Comment by josepowera** [comment]
@fortypercnt thx!   Any yes, looking forward to see solution with "last 30s" as context.
